### ISSUE TITLE
add support for alternate providers

### ISSUE THREAD

**Issue by hackerhasid** [fgrehm/vagrant-notify#13]
right now it looks like virtualbox is assumed (baked right into [plugin.rb](https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/plugin.rb)) - i use the [parallels provider](https://github.com/Parallels/vagrant-parallels) and would love to see support for other providers.

i'm happy to fork and try to take a stab at this but would love to hear your thoughts first though - i haven't developed any vagrant plugins before and i'd love to hear your thoughts before i jump it (for example, would this even be possible lol!)

one thing to note actually is that [port forwarding isn't yet implemented in the parallels provider](https://github.com/Parallels/vagrant-parallels/issues/57). not sure that's even relevant since this seems to work the opposite way around (creating a server on the host and sending data from the guest) but i figured it's worth mentioning.

**Comment by alpha01** [comment]
It only took over 2.5 years, but as of v.0.5.2 vagrant-notify now also supports Docker, VMWare Fusion, Parallels, and LXC providers.
