### ISSUE TITLE
support for windows hosts

### ISSUE THREAD

**Issue by spescina** [fgrehm/vagrant-notify#14]
on vagrant up I have this error:
"fork() function is unimplemented on this machine"

**Comment by bahjaat** [comment]
+1
Windows 8 / 8.1 has a notification window build in. Info @ http://windows.microsoft.com/en-gb/windows-8/how-manage-notifications
Gulp-notify is working out of the box on my console directly. Hope to welcome it via Vagrant. Would be awesome.

**Comment by Stanzilla** [comment]
Yup would be great to get support for the native Windows8+ notifications!

**Comment by fgrehm** [comment]
Sorry for the silence here but unfortunately I don't have a windows machine around to try this out neither I have been using this plugin recently.

If anyone is able to put together a PR I'd love to review it and bring it in, but keep in mind that my plan is to eventually start making use of https://github.com/fgrehm/notify-send-http from within this plugin, so if a PR is made to that project it would be perfect!

**Comment by insign** [comment]
+1

**Comment by alpha01** [comment]
The new notification server that is part of vagrant-notify 0.5.0 works on Windows 7. I haven't tested Windows 8/8.1 or Windows 10, so I'm not familiar with the their respective native notifications. If they include a userland application that you can easily call, then it's just a matter of creating a notify-send.exe  binary, available on `path`. See example https://github.com/fgrehm/vagrant-notify/tree/master/examples#windows
