### ISSUE TITLE
Automagically disable the plugin for cloud providers

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-notify#15]
Depends on https://github.com/fgrehm/vagrant-notify/issues/6

See vagrant-cachier for reference.

**Comment by alpha01** [comment]
As of vagrant-notify v0.5.1, the plugin is automatically disabled for cloud providers. https://github.com/fgrehm/vagrant-notify/commit/7563cec5cb4aed633d4db591cd946becd186e531
