### ISSUE TITLE
Error obtaining client ip address

### ISSUE THREAD

**Issue by hugoduraes** [fgrehm/vagrant-notify#16]
Hi,

I'm getting an error while obtaining the client IP address from the environment variable SSH_CLIENT. The error is:

```
Error: Command failed: /usr/bin/notify-send:43: private method `split' called for nil:NilClass (NoMethodError)
```

Any clue on what is causing this?

Thank you.

**Comment by fgrehm** [comment]
[This](https://github.com/fgrehm/notify-send-http/blob/c2e996eb8740f4733613ea6556ed92dc073523b8/vagrant-installer.sh) will make up for the new configuration process.

**Comment by alpha01** [comment]
Closing this issue. As of v0.5.0, the notification server no longer relies on an active ssh connection to send messages. 

See [notify-send.erb](https://github.com/fgrehm/vagrant-notify/blob/master/files/notify-send.erb#L42-46) to view how client ip address is determine.
