### ISSUE TITLE
Stopping notification server

### ISSUE THREAD

**Issue by hugoduraes** [fgrehm/vagrant-notify#18]
```vagrant halt``` is not stopping the notification server.

Using Vagrant 1.6.3 on Mac OS X 10.9.3.

**Comment by russjaguar** [comment]
I was having this issue on OS X 10.10.1, with Vagrant 1.6.5. I just updated to the latest version of Vagrant (1.7.2 at this time) and I can confirm that when suspending, the notify server is left running and will build up and eventually start blocking Vagrant actions until all the running notify servers are killed. The notify servers are ended properly when using the halt action.

**Comment by callistino** [comment]
Can I run the tcp server without vagrant?

**Comment by fgrehm** [comment]
@callistino these days I'd recommend using https://github.com/fgrehm/notify-send-http#vagrant. I'm still thinking about using that as the foundation of this plugin but haven't made my mind yet... @Driklyn has [reported that he has been using it with great success](https://github.com/fgrehm/vagrant-notify/issues/17#issuecomment-70153563) and I'd say you give it a try too.

The more people giving me a :+1: on that, the more I'm inclined to think about this plugin a bit more ;)

**Comment by alpha01** [comment]
Bug fixed on v0.5.0
