### ISSUE TITLE
terminal-notifier is not part of the bundle. Add it to Gemfile. (Gem::LoadError)

### ISSUE THREAD

**Issue by stuffaboutpete** [fgrehm/vagrant-notify#19]
I'm getting the following error whilst trying to get this workflow set up.

```bash
/Applications/Vagrant/embedded/gems/gems/bundler-1.5.3/lib/bundler/rubygems_integration.rb:240:in `block in replace_gem': terminal-notifier is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
from /usr/bin/terminal-notifier:22:in `<main>'
```

All I've done is install the plugin ```vagrant plugin install vagrant-notify```, created the following script at ```/usr/local/bin/notify-send``` (on OSX) and run ```vagrant up```.

```bash
#!/bin/bash
terminal-notifier -title "Vagrant Machine" -message "$*"
```

The machine provisions without issue and then the error appears whenever notify-send is called on the virtual machine. In this case it's a 32bit Ubuntu 13.10 machine.

I can't get get my head around what the error is telling me; it seems like the host vagrant installation doesn't have access to a 'terminal-notifier' command. But I wouldn't know how to fix or get round that.

Any thoughts?

**Comment by fgrehm** [comment]
Support for Mac OS has just landed into notify-send-http. This will be fixed when this plugin gets updated to use that.

**Comment by richardriman** [comment]
I have solution for terminal-notifier. I solved it this way:

`
#!/bin/bash
shift
/usr/local/bin/terminal-notifier -title "Vagrant Machine" -message "$*"
`

It's because notify-send sends '--' as a first argument & terminal-notifier doesn't know this syntax.

**Comment by alpha01** [comment]
Closing. Use https://github.com/fgrehm/vagrant-notify/blob/master/examples/osx/notify-send_terminal-notifier
