### ISSUE TITLE
add more details to the built-in notifications

### ISSUE THREAD

**Issue by hardyoyo** [fgrehm/vagrant-notify#21]
This line is nice:

https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/action/notify_provisioning_status.rb#L10

But it results in messages like this:
 "Provisioning with shell..."
and
 "Finished provisioning with shell." 

Which is cool, however, it would be even better if we had a bit more of an idea of what each shell provisioner is doing. For Vagrantfiles with many inline shell provisioners, you get lots of notifications, but no detail, which isn't very useful. I know, stop using inline shell provisioners... Perhaps, someday. But, a little more detail for these notifications would be handy for many people, I think?

**Comment by fgrehm** [comment]
Recent vagrant versions have support for provisioner names, that's the best thing we can do I guess, tagging this as an enhancement

**Comment by alpha01** [comment]
vagrant-notify now correctly notifies the start and finished provision status with the actual provisioner name as part of the notification.
 
I'm against adding notifications on exactly what the provisioner is doing. Mainly because you can already see this from the terminal, so it would be redundant. On top of that, depending on the provision environment, this could lead to an insane amount of unnecessary notifications.

**Comment by hardyoyo** [comment]
I'm unclear how asking for slightly more detail than "shell" would result in an "insane amount of unnecessary notifications." :-) I have tried using a :name for a few inline shell provisioners, but vagrant-notify does not appear to use the names. I'll go look at the code and see if I can modify it to use a name, if it's provided.

**Comment by alpha01** [comment]
Ok, I see what you're mean now. I originally misunderstood and thought you wanted vagrant-notify to display output from the shell provisioner.

This should be relatively simple to implement. By looking at [shell provisioner code](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/shell/config.rb#L47) the _name_  shell provision block configuration should be available to varant-notify via `env[:provisioner].config.name`

Is something like this you had in mind?
`[BOXNAME] Provisioning with "shell (PROVIONNAME)"`
`[BOXNAME] Finished provisioning with "shell (PROVIONNAME)"`

**Comment by hardyoyo** [comment]
Yep, that's it exactly. Wish I had more time to devote to this notion. I mostly use the boxes after they're done provisioning, to do actual work, but it would be nice to keep an eye on a re-provision by watching notifications... it beats keeping an output window up and skimming the output. Like watching paint dry. :-)

**Comment by alpha01** [comment]
vagrant-notify 0.5.4 or above will now include the shell name in the provision notify message.
