### ISSUE TITLE
Notification when provisioning fails

### ISSUE THREAD

**Issue by patcon** [fgrehm/vagrant-notify#23]
This is a great plugin! Any obstacle to adding a handler for provisioner failures? Seems to just notify on start and successful completion atm.

**Comment by fgrehm** [comment]
That would be great! I just need to deal with GH-17 first :grin:

**Comment by alpha01** [comment]
Feature has been added and set for v0.5.3 release  https://github.com/fgrehm/vagrant-notify/commit/f65b162078b122a749b432adad6ffb2e444d68af
