### ISSUE TITLE
vagrant notify stops homestead from working

### ISSUE THREAD

**Issue by patrick-evolabs** [fgrehm/vagrant-notify#28]
After installing vagrant notify and running vagrant, I get the following error message when running vagrant up. 

```
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating
```

I can still access it with ssh, but the file mapping is not occurring, so it's not much use to me.  
Uninstalling the plugin solves the issue, but I would rather use it of course!

Homestead : 0.4.2 and 0.4.4 don't work
Vagrant :  1.8.1
Virtualbox : 5.0.18_Ubuntu r106667
OS: Ubuntu 16.04
Vagrant-Notify: 0.4.0

**Comment by alpha01** [comment]
vagrant-notify 0.5.0 was just released. Try updating to the newer version.

**Comment by valdrox** [comment]
Thanks for the heads up. 
That fixed the issue!

**Comment by alpha01** [comment]
Closing
