### ISSUE TITLE
Doesn't work when guest missing ruby

### ISSUE THREAD

**Issue by Fuxy22** [fgrehm/vagrant-notify#35]
If the guest is missing ruby like for instance on a laravel/homestead box the plugin does't attempt to install ruby or warn about it and instead it just fails to work.

Is this intended?

**Comment by alpha01** [comment]
Ruby is required to be installed on the guest instance. You brought up a good point, the plugin should at least display a warning if Ruby is not installed. I'll leave this issue open until I added this feature.

This Ruby dependency on the guest instance kind of sucks in my opinion.  A while ago I thought of possibly creating a universal `notify-send` binary  port of [notify-send.erb](https://github.com/fgrehm/vagrant-notify/blob/master/files/notify-send.erb) for `vagrant-notify` written in golang to eliminate this dependency problem, but I haven't had the time to learn the language.

**Comment by alpha01** [comment]
vagrant-notify 0.5.4 or above will now display a warning message if Ruby is not installed on the guest.
