### ISSUE TITLE
"sh: notify-send: command not found" in homestead on MacOS X

### ISSUE THREAD

**Issue by MekDrop** [fgrehm/vagrant-notify#36]
Strange thing that this happens after I did `sudo DEBIAN_FRONTEND=noninteractive apt-get install -q -y ruby-full` and everything should work. However this for me works if I run on windows host.

I'm unsure if this is some plugin issue or virtualbox or vagrant... do you have any ideas?

**Comment by alpha01** [comment]
Unless the plugin is [disabled](https://github.com/fgrehm/vagrant-notify#configuration), each time the guest VM starts/stops; a Ruby script get's copied over to `/usr/bin/notify-send` onto the guest VM. Is this not happening?

**Comment by MekDrop** [comment]
It seams that happens. Also there is `/usr/bin/notify-send.bkp` file. And I think it should work but for unknown reason I'm getting such error. Like I said. same vagrant file doesn't have problem when I'm running on windows.

**Comment by alpha01** [comment]
It sounds like the guest's notify-send is not able to find the `notify-send` on your host MacOS system. Have you created a script called  `notify-send` and have it saved anywhere on your PATH? I provide some examples here https://github.com/fgrehm/vagrant-notify/tree/master/examples

It is important that the script on your MacOS system is named **notify-send** and the execute permission is set to it. Because that's what the notification server runs when it receives messages from the guest VM https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb#L48

**Comment by MekDrop** [comment]
Good point! Tomorow at work I'll try this. Still such message is not very informative.

**Comment by MekDrop** [comment]
It seems that was issue. Somehow I have forgot to add a script. I also modified one of MacOS X examples to be able to run without any external apps with build-in AppleScript support. 

Still, I would like to make somehow this error message more informative but i'm unsure how to do.

**Comment by alpha01** [comment]
Thanks for the AppleScript support!

To get a more relevant error message, might need to modify either guest's [notify-send](https://github.com/fgrehm/vagrant-notify/blob/master/files/notify-send.erb#L58) or the actual [notification server](https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb).

I think the easiest and best approach is to have the plugin display a warning if it doesn't detect a `notify-send` anywhere on the host's PATH prior to starting the notification-server.

**Comment by MekDrop** [comment]
I think if we could change `system("notify-send #{args}")` line (in `https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb`) into `puts "Warning! Notify send on host os not found!" if system("notify-send #{args}").nil?` at least partially should solve this issue. If command is not found system returns nil.

**Comment by alpha01** [comment]
closing
