### ISSUE TITLE
Add support for libvirt provider

### ISSUE THREAD

**Issue by steve-todorov** [fgrehm/vagrant-notify#47]
Hi,

Are there plans for adding support for the [vagrant-libvirt/vagrant-libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt) provider?  

I just tried the plugin and it failed with:

```
==> vm: libvirt provider is not supported by vagrant-notify. Please feel free to open a new issue https://github.com/fgrehm/vagrant-notify/issues
```

**Comment by alpha01** [comment]
Not in the immediate moment, I do very little work with Vagrant nowadays so it may take some time for me to work on this. Feel free to submit a PR.

**Comment by fgrehm** [comment]
Sorry for the silence here @steve-todorov but I've recently decided to archive the project due to the lack of maintenance and interest. That was also backed by @alpha01 who was maintaining it.

Sorry it took so long to get back to ya!
