### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-notify#49]
@alpha01 hey there! how's it going? Long time no chat :beers: 

Are you still using this plugin and is willing to maintain it moving forward? I'm going through some old projects I own and making sure they are still healthy when it comes to interest and maintainers.

I am considering archiving this one unless I know for sure that ppl are using and it has a maintainer with some level of commitment :smiley: :metal:

**Comment by alpha01** [comment]
@fgrehm I think this project can be archived. I haven't used it in years, and the repo/project hasn't seen much activity either.

Thanks a lot for allowing me to commit to this project, it was a pleasure working on it.

**Comment by fgrehm** [comment]
Thanks Tony! I'll do that now. Thanks for helping with it!
